name = "af-theme"
license = "MIT"
licenselink = "https://opensource.org/licenses/MIT"
description = "Tema oscuro terminal para af.dev"
homepage = "https://github.com/af-simicic"
min_version = "0.110.0"

[author]
  name = "Andrés Fuentes"
